[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "55ibTnYbkZZPhuSxPtsG2v1t76gAjHxDxLbj3q6EikPo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/chrisjgr/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
